#ifndef TEXTURESNAME_H
#define TEXTURESNAME_H

enum class TexturesName {
    BACKGROUND,
    HIGHLIGHT,
    BLACK_BISHOP,
    BLACK_KING,
    BLACK_KNIGHT,
    BLACK_PAWN,
    BLACK_QUEEN,
    BLACK_ROOK,
    WHITE_BISHOP,
    WHITE_KING,
    WHITE_KNIGHT,
    WHITE_PAWN,
    WHITE_QUEEN,
    WHITE_ROOK,
    BLACK_SQUARE,
    WHITE_SQUARE,
    FOCUSED_SQUARE,
    CHECKED_SQUARE,
    CONTROL_FOCUSED,
    CONTROL_UNFOCUSED
}

#endif